title: Churlie
email: peter@forret.com
description: Manage your web sites
baseurl: "/"
url: "https://jekyll.churlie.com"
twitter_username: pforret
github_username:  pforret

highlighter:      rouge
permalink:        pretty

paginate:         10

author:
  name: 'Peter Forret'
  url: https://twitter.com/pforret

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - hyde
  - .idea/
